package com.project.myPortfolioBk.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Data // for automatic getters and setters
@Entity
public class Project {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // id autogenerated

    private String title; // project title
    private String description; // project description
    private String github_Url; // github URL
    private String techStack; // framework used
}
