[project]
name = "fastapi-app"
version = "0.1.0"
description = "FastAPI Backend"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "fastapi-cli",
    "uvicorn[standard]",
    "pymongo",
    "python-dotenv",
    "python-multipart",
    "passlib[bcrypt]",
    "bcrypt==4.0.1",
    "PyJWT",
    "pydantic",
]